### ISSUE TITLE
Filter_gen in GROUP produce inf weights

### ISSUE THREAD

**Issue by mads-bertelsen** [McStasMcXtrace/McCode#797] opened 2019-06-03 08:14 UTC
When using Filter_gen in a group some ray weights are adjusted to infinite. Cases with memory errors also observed. Running McStas 2.5.
The issue happens regardless of how the components are placed with respect to one another.

**Comment by willend** [comment] 2019-06-03 08:37
Instrument file demonstrating the issue attached:
[filter_bug.zip](https://github.com/McStasMcXtrace/McCode/files/3246587/filter_bug.zip)

(I have seen it run with two different types of errors

1. a segfault: 
<pre>
(Table_Read_Offset)
filter_bug.out(10272,0x111e155c0) malloc: *** error for object 0x7fd4ae500630: pointer being freed was not allocated
filter_bug.out(10272,0x111e155c0) malloc: *** set a breakpoint in malloc_error_break to debug
# McStas 2.5 - Dec. 12, 2018: [pid 10272] Signal 6 detected SIGABRT (Abort)
# Simulation: filter_bug (filter_bug.instr) 
# Breakpoint: filter_center (Init) 0.00 % (       0.0/ 1000000.0)
# Date:      Mon Jun  3 10:35:33 2019
# Started:   Mon Jun  3 10:35:33 2019
# Last I/O Error: No such file or directory
# McStas 2.5 - Dec. 12, 2018: Simulation stop (abort).
</pre>

2. mention of infinity
<pre>
WARNING: Inf detected in component/file Lmon Lmon.dat
Detector: Lmon_I=0 Lmon_ERR=0 Lmon_N=0 "Lmon.dat"
WARNING: Inf detected in component/file PSD PSD.dat
Detector: PSD_I=0 PSD_ERR=0 PSD_N=0 "PSD.dat"
</pre>
)

**Comment by mads-bertelsen** [comment] 2019-06-04 07:20
The bug is not connected to GROUP as initially assumed, it just occurs if more than one filter is used in the same instrument.

[filter_bug_no_group.instr.zip](https://github.com/McStasMcXtrace/McCode/files/3250996/filter_bug_no_group.instr.zip)

**Comment by ebknudsen** [comment] 2019-06-04 09:43
This appears to work fine as it should on linux. 

Likely the issue is connected to the Table_Rebin call in INITIALIZE. One change between the versions was a caching behaviour of data files to avoid readin the same data file from disk several times.

**Comment by willend** [comment] 2019-06-04 09:45
Does indeed look like a macOS-ism of sort. 
(I reproduce the behaviour both with the McStas-2.5-shipped gcc, clang and my gcc-8 from /usr/local/)

**Comment by willend** [comment] 2019-11-11 08:27
@mads-bertelsen and @ebknudsen it looks like this has been fixed through changes in read_table-lib on master.

@mads-bertelsen could you try this beta of 2.6: http://tmp.mcstas.org/mcstas-2.6rc01.tgz 
and let me know if the problem persist with that version?

**Comment by mads-bertelsen** [comment] 2019-11-18 12:24
@willend The problem is indeed fixed in the 2.6 release candidate you sent. Sorry for the delay in testing.

**Comment by willend** [comment] 2019-11-18 13:03
Excellent, I close the issue then

**Closed by willend** 2019-11-18 13:03 UTC
Labels: McStas 2.5
