### ISSUE TITLE
mxplot-pyqtgraph: The plot sweep series function plots identical copies of the same plot

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#387] opened 2017-01-25 13:04 UTC
On a debian testing system there's an issue with mcplot-pyqtgraph when "ctrl-clicking" in a plot to go into the plot sweep series-mode. It merely plots identical copies of (I think) the last sweep step.

Attached is a sweep that has this problem:

[Test_husimo_lens_20170124_224724.zip](https://github.com/McStasMcXtrace/McCode/files/729646/Test_husimo_lens_20170124_224724.zip)

This does not appear to be a problem with a standard BNL_H8 scan using mcplot.

**Comment by climbcat** [comment] 2017-01-25 15:00
When ctrl-clicking on psd0_I, different images are displayed on the subplots. When ctrl-clicking the others, they all look the same. I'll debug-print the filename of each peace of plot data, when it is plotted, to verify.

**Comment by climbcat** [comment] 2017-01-25 15:04
Actually, the data are all different, which can be verified by scrutinizing the colors of the pixels in e.g. the upper-left intersection of the beam proper with the monitor. blue-orange-red vs. blue-red-yellow, etc. The scale tickmarks on the colorbar also move a little bit from plot to plot:)

**Comment by willend** [comment] 2017-01-26 07:28
Agreed @climbcat, when carefully looking - even though the monitor output looks the same in 3 of 4 monitors, it isn't really... :-) Closing.

**Comment by ebknudsen** [comment] 2017-01-26 09:16
Hmm - granted they are slightly different - but the actual data are rather different. I've attached screenshots (screen1) of a plot series of the psd05 monitor (the upper right one) by 
> m(xc)plot Test_husimo_lens__20170124_224724/ - then ctrl-click the monitor
where the plots are almost identical and also the direct plots of first (screen 2) and last (screen 3) scan step.
> m(cx)plot  Test_husimo_lens__20170124_224724/0 and Test_husimo_lens__20170124_224724/20
As you can see they are not even similar - although the signal is weak - could it be that there is some buffer is not zeroed and simply added to instead? Dunno - will investigate further.
![screen1](https://cloud.githubusercontent.com/assets/855956/22325856/82313e64-e3b0-11e6-9191-7610fd935ce0.png)
![screen2](https://cloud.githubusercontent.com/assets/855956/22325857/82504386-e3b0-11e6-8964-c8afbf03e5c6.png)
![screen3](https://cloud.githubusercontent.com/assets/855956/22325858/8251b23e-e3b0-11e6-8d64-fa2ee23264bd.png)

**Comment by climbcat** [comment] 2017-01-26 10:40
What I think happens is, that the position of the monitors in the overview sweep plot (e.g. "."), vs. the local sim plot (e.g. "20") is not the same. Therefore, the two psd monitors containing "faint" images might be confused with one another. One contains images of varying intensity, however, and the other one differs slightly in faintness/intensity.

However, the two images to the right do look exactly the same to my eyes. This is probably as intended.

![ex](https://cloud.githubusercontent.com/assets/11196009/22328314/d45350f0-e3bb-11e6-855a-0ba6a49579fc.png)

**Comment by climbcat** [comment] 2017-01-31 10:18
The data doesn't appear to be loaded multiple times, so we should close this issue. It does appear, however, that the order of data presentation is inconsistent (and wrong). I have opened another issue for that.

**Closed** 2017-03-20 10:38 UTC
Labels: McXtrace 1.3, MUST be addressed for McXtrace 1.4
