### ISSUE TITLE
mcdisplay -pyqtgraph doesn't allow the instrument name to contain "instr" anywhere

### ISSUE THREAD

**Issue by jfkcooper** [McStasMcXtrace/McCode#527] opened 2017-07-19 15:56 UTC
If an instrument has the letters instr somewhere in its name, it cannot be parsed by in mcdisplay using pyqtgraph, it gives the message "Syntax error in input!" followed by parsetreeroot must be of type "instdeftree".
I haven't seen this issue using mcrun, or if mcdisplay uses -pl, so I guess it is the sanitisation of the name somehow, but am not sure where/what.
![image](https://user-images.githubusercontent.com/28106479/28376884-2db8edec-6ca3-11e7-934b-793df0c73866.png)

**Comment by climbcat** [comment] 2017-07-19 16:26
Hi! Thanks for reporting this. The bug was due to a '.' in a regex where '\.' was intended, and has been fixed by ecf84add95a241135747e8c614a0d83e56cd723b.

**Comment by jfkcooper** [comment] 2017-07-19 16:32
Confirmed that this is indeed the issue. Thanks

**Closed** 2017-08-15 11:01 UTC
