### ISSUE TITLE
python-mcdisplay-webgl: parsing using a low number of ray with inspect problem

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#446] opened 2017-04-26 14:26 UTC
Crashes when using inspect with webgl mccdisplay and a low number of rays.

**Comment by mducle** [comment] 2017-04-26 14:40
Example instrument file: 
[Ex_4_2_chopper.zip](https://github.com/McStasMcXtrace/McCode/files/958716/Ex_4_2_chopper.zip)

Run with:

```
mcdisplay-webgl Ex_4_2_chopper.instr --no-output-files --inspect=TOF1 -n 100  freq=10  Theta0=5
```

will fail with an `IndexError` in line 128 of `mccodelib/instrgeom.py`. 

Running with `-n 1e5` works (usually). The above error occurs on both Linux (Ubuntu 16.04) and Windows 10. 

There is an additional error on Windows concerning a `divbyzero` (more details to follow).

**Comment by willend** [comment] 2017-04-26 15:13
Thanks @mducle, also reproducible on macOS with 

<pre>
mcdisplay-webgl PSI_DMC.instr -n1 --inspect=sample
</pre>
(visualisation works OK without use of --inspect)

This gives
<pre>
starting particle parsing
ended particle parsing
list index out of range
Traceback (most recent call last):
  File "/Applications/McStas-2.4pre01.app/Contents/Resources/mcstas/2.4pre01/bin/../tools/Python/mcdisplay/webgl/mcdisplay.py", line 197, in <module>
    raise e
  File "/Applications/McStas-2.4pre01.app/Contents/Resources/mcstas/2.4pre01/bin/../tools/Python/mcdisplay/webgl/mcdisplay.py", line 192, in <module>
    main(args)
  File "/Applications/McStas-2.4pre01.app/Contents/Resources/mcstas/2.4pre01/bin/../tools/Python/mcdisplay/webgl/mcdisplay.py", line 166, in main
    write_browse(instrument, raybundle, dirname, args.nobrowse)
  File "/Applications/McStas-2.4pre01.app/Contents/Resources/mcstas/2.4pre01/bin/../tools/Python/mcdisplay/webgl/mcdisplay.py", line 128, in write_browse
    json_neutr = 'MCDATA_particledata = %s;' % json.dumps(raybundle.jsonize(), indent=0)
  File "/Applications/McStas-2.4pre01.app/Contents/Resources/mcstas/2.4pre01/bin/../tools/Python/mcdisplay/webgl/../../mccodelib/instrgeom.py", line 288, in jsonize
    initial_speed = self.rays[0].get_speed()
IndexError: list index out of range
</pre>
Will you have a look @climbcat ?

**Comment by willend** [comment] 2017-04-26 15:14
The -pyqtgraph crashes with a similar error, so the issue is likely in mccodelib somewhere
<pre>
starting particle parsing
ended particle parsing
q            - quit
p            - save png
s            - save svg
space        - next ray
click        - enter subplot
right-click  - exit subplot
h/F1         - show component list
integer division or modulo by zero
Traceback (most recent call last):
  File "/Applications/McStas-2.4pre01.app/Contents/Resources/mcstas/2.4pre01/bin/../tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 566, in <module>
    raise e
  File "/Applications/McStas-2.4pre01.app/Contents/Resources/mcstas/2.4pre01/bin/../tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 561, in <module>
    main(args)
  File "/Applications/McStas-2.4pre01.app/Contents/Resources/mcstas/2.4pre01/bin/../tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 538, in main
    sys.exit(gui.run_ui(instrument, raybundle.rays))
  File "/Applications/McStas-2.4pre01.app/Contents/Resources/mcstas/2.4pre01/bin/../tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 393, in run_ui
    self._display_nextray()
  File "/Applications/McStas-2.4pre01.app/Contents/Resources/mcstas/2.4pre01/bin/../tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 456, in _display_nextray
    ray = self.rays[self.ray_idx % len(self.rays)]
ZeroDivisionError: integer division or modulo by zero
</pre>

**Comment by willend** [comment] 2017-04-26 15:15
I think the issue simply occurs if there are no neutrons at all?

**Comment by climbcat** [comment] 2017-04-27 12:29
This should be fixed now.

I found two unrelated bugs in the case that no neutrons were recorded from the simuation - due to inspect or n1. The instrgeom.py line 288 bug was a missing empty-list-check. Another bug was the inability to visualize a particle ray list of lenth one, in the js webgl mcdisplay version. The pqtg front-end seems to work as intended.

The "--inspect" implementation may or may not have worked with "n1" runs, but at least the current implementation seems to work as intended in my tests.

@mducle thanks for your report. Could you please elaborate what you mean by "Running with -n 1e5 works (usually)." I am a bit worried about the "usually" comment there and would like to fix any bugs you find :-)

**Comment by mducle** [comment] 2017-04-27 12:34
@climbcat "usually" - I tried it about 5 times with `-n 1e5` and it gave the error once, and the other times it worked - I guess because that one time no neutron trajectories managed to get through the instrument.

**Comment by climbcat** [comment] 2017-04-27 12:41
Ok, in that case it probably wont happen again. If it does I'd be happy to know. BR

**Comment by mducle** [comment] 2017-04-27 20:21
Works ok for me now with `-n 1` for both `webgl` and `pyqtgraph`.

**Closed** 2017-05-02 09:49 UTC
