### ISSUE TITLE
mcgui-py, further communication between main window and editor

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#183] opened 2015-11-18 14:41 UTC
* If run is pressed, unsaved changes in the editor are currently not taken into account (run should spawn save in this case)
* File -> New should close any existing editor window

**Comment by willend** [comment] 2016-01-15 10:00
@climbcat did you do anything here already?

**Comment by climbcat** [comment] 2016-01-15 12:40
not yet

**Comment by climbcat** [comment] 2016-01-15 22:02
it's done now, fixed another bug as well (closedown could be cancelled by editor window, resulting in only that window being open..)

**Comment by willend** [comment] 2016-01-28 14:20
@climbcat says that sometimes mcgui-py erases the instrument file contents for no reason... :-)

**Comment by climbcat** [comment] 2016-02-04 08:45
I can't seem to reproduce the error, or find any other bugs. It's probably fine, but we should keep an eye out

**Comment by climbcat** [comment] 2016-02-12 12:34
There was a bug, and I fixed it. The problem was that the editor window was not being properly initialized with instrument data. But at the same time it was being used as an authoritative source of instrument text when compiling the instrument... now fixed.

**Closed by climbcat** 2016-02-12 12:34 UTC
Labels: C: GUI, enhancement, McStas 2.3

**Comment by willend** [comment] 2016-02-12 12:35
:+1:
