### ISSUE TITLE
Fatal error: memory exhausted

### ISSUE THREAD

**Issue by haodengfrm2** [McStasMcXtrace/McCode#318] opened 2016-10-13 11:42 UTC
"*** No directory given - placing data in E:/From-Dr-Andreas-Ostermann/politest3_
new2_AO_20161013_133538 ***
Translating instrument definition 'E:/From-Dr-Andreas-Ostermann/politest3_new2_A
O.instr' into C ...
mcstas -I E:/From-Dr-Andreas-Ostermann -t -o E:/From-Dr-Andreas-Ostermann/polite
st3_new2_AO.c E:/From-Dr-Andreas-Ostermann/politest3_new2_AO.instr

Fatal error: memory exhausted during allocation of size 2000000.

Program aborted.
** Error exit **
Press any key to continue . . .
"

Computer: Dell Precision Tower 3620, CPU Xeon E3-1240, RAM 16GB, hard disk 256G MBR SSD + 3TB GPT HHD
![memory exhausted error](https://cloud.githubusercontent.com/assets/22814682/19347759/ca342a90-914a-11e6-995a-20431bc820f2.png)

**Comment by willend** [comment] 2016-10-15 09:48
Hi there,

Thank you for reporting this - who am I talking to? :-)

It is a bit hard to know without access to your instrument file and any extra bits and pieces, but the error 

<pre>Fatal error: memory exhausted during allocation of size 2000000.</pre>

is from the code-generator, specifically line 41 of memory.c. Is your instrument file a really big beast with many components maybe?

Please send me an archive with everything needed to reproduce your error and I shall have a look.

Best,
Peter Willendrup

**Comment by haodengfrm2** [comment] 2016-10-17 07:08
Hi Dr. Peter,

I'm Dr. Hao Deng, postdoc for Poli and HEiDi @FRM II. Attached 
compressed file includes all the instrument and component files. Yes you 
are right, it is with many components. It comes from one of my 
colleague, and in my mind its strategy is to simulate a polarized bender 
with many piece of small straight ones.

By the way, when I change to Mcstas 2.2a instead of 2.3, this error 
doesn't exist.

Thanks very much and best regards!

Hao

**Comment by willend** [comment] 2016-10-18 07:36
Hello again,

I have now been able to reproduce the issue: It clearly relates to the code generator, indeed seems connected to McStas 2.3 and not 2.2a (and earlier) - but is on the other hand only reproducible on Windows...(!)

Will be back with more information later.

Peter

**Comment by willend** [comment] 2016-10-18 09:20
Hi again,

I have tracked down your bug to be related to this commit: https://github.com/McStasMcXtrace/McCode/commit/61ce6872e6c543e20d41da812fcdfe77940c63ad
- which defines the maximum list length e.g. maximum length of included files.

It seems that the issue is 32 vs 64 bit related, these days we build 64 bit for everything but Windows.

I have built a 64-bit code generator for McStas 2.3 which you can download here:
http://download.mcstas.org/mcstas-2.3/windows/64-bit_code_generator/

Simply unpack the tgz and cherry-pick bin\mcstas.exe for replacement of the mcstas.exe you have in c:\McStas-2.3\bin

For now I will close the issue - but we can reopen if you are still having problems.

Best,
Peter

**Closed by willend** 2016-10-18 09:20 UTC

**Comment by haodengfrm2** [comment] 2016-10-18 11:35
Hi Peter,

Sorry for replying you late, because of the starting of our reactor. 
Thank you very much for solving my problem! I would try it soon.

Thanks very much and best regards!

Hao
