### ISSUE TITLE
detector

### ISSUE THREAD

**Issue by eddymaoui** [McStasMcXtrace/McCode#793] opened 2019-04-22 13:14 UTC
hi
I need a detector that provides a two theta diagram according to nobre of events
x=2 theta
y=nobre of events
thanks

**Comment by willend** [comment] 2019-04-25 14:01
Hello @eddymaoui,

This is exactly what the solution in https://github.com/McStasMcXtrace/McCode/issues/792 will give you (intensity rather than the statistical neutron-ray events is what you should measure, please consult chapter 2 of the McStas manual, i.e. http://www.mcstas.org/documentation/manual/mcstas-2.5-manual.pdf or as installed on your own computer.) 

Closing this one as it is a duplicate of the earlier issue

**Closed by willend** 2019-04-25 14:01 UTC
