### ISSUE TITLE
Problem compiling with MCPL on Ubuntu 17.04

### ISSUE THREAD

**Issue by letibdesneiges** [McStasMcXtrace/McCode#547] opened 2017-09-28 14:25 UTC
Hi,

I consistently get the below error when trying to compile instrs with MCPL use:
<pre>
/usr/bin/ld: /usr/share/mcstas/2.4.1/libs/mcpl/libmcpl.a(mcpl.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
** Error exit **
</pre>

Peter had a look here @ IKON13 with no success, test instrs, non-mpi, normal gcc, all fails :-)

**Comment by letibdesneiges** [comment] 2017-09-28 14:33
Peter checked a bit further: seems to be gcc-6 specific, exchanging for a 4.9 helped...

**Comment by ebknudsen** [comment] 2017-11-16 06:51
I can confirm that it works with gcc-5 as well. I does not work with gcc-7. It would appear that it has something to do with the way the mcpl-libs are compiled.

**Comment by willend** [comment] 2017-11-16 08:18
I remember also trying to compile MCPL libs with the gcc-6 compiler and suggested -fPIC, but as I remember no luck.

We should check this a bit more systematically and report a bug to MCPL

**Comment by ebknudsen** [comment] 2017-11-16 12:45
It don't think it is an MCPL-bug. We set the compilation options ourselves in CMakeLists.txt.

That said - I've been recompiling libmcpl.a with and without "-fPIC" set today with both gcc6 and 7 and I cannot reproduce the bug. That is - it happens with the shipped mcpl but not with my newly compiled ones. Where did the shipped package get built?

**Comment by ebknudsen** [comment] 2017-11-16 12:58
So a workaround for this using gcc 6.4 appears to be:
copy the mcpl.c and mcpl.h files from the distribution somewhere, compile them locally, and copy back:
For a debian system this would be:
> mkdir tmp; cd tmp
> cp /usr/share/mcstas/2.4.1/libs/mcpl.* .
> gcc -c -I. mcpl.c
> ar -r libmcpl.a mcpl.o
> [sudo] cp libmcpl.a /usr/share/mcstas/2.4.1/libs/

**Comment by ebknudsen** [comment] 2017-11-20 10:20
closing as a workaround exists - will reopen if this persists

**Comment by willend** [comment] 2017-12-07 13:54
We might 

1) add something about this to the Wiki
2) compile our libs install-time (postinstall script) - done already on Windows

**Comment by ebknudsen** [comment] 2017-12-07 14:46
Wiki page added

**Comment by ebknudsen** [comment] 2018-01-18 09:30
Reopening as a similar error reported by Felix @ ESS Bilbao, did not get fixed by it - instead it generated a huge amount of other errors.

**Comment by willend** [comment] 2018-12-13 08:41
@ebknudsen status?

**Comment by willend** [comment] 2019-11-04 20:07
I think we close this one, seems we would have had more complaints if reported bug was still relevant.

**Closed by willend** 2019-11-04 20:07 UTC
